/**
 * MYSTIQUE COMPASS — Psychomatrix Plane Analysis
 *
 * Four Planes of Expression derived from the psychomatrix grid:
 * Mental (3-6-9), Physical (1-4-7), Emotional (2-5-8), Intuitive (1-5-9)
 *
 * ALL TEXT IS VERBATIM.
 */

export interface PlaneAnalysis {
  name: string;
  score: number;
  maxScore: number;
  percentage: number;
  cells: number[];
  level: 'Deficient' | 'Developing' | 'Balanced' | 'Dominant' | 'Overwhelming';
  interpretation: string;
}

export interface PlaneResult {
  mental: PlaneAnalysis;
  physical: PlaneAnalysis;
  emotional: PlaneAnalysis;
  intuitive: PlaneAnalysis;
  dominantPlane: string;
  weakestPlane: string;
  synthesis: string;
}

function getLevel(percentage: number): PlaneAnalysis['level'] {
  if (percentage <= 10) return 'Deficient';
  if (percentage <= 30) return 'Developing';
  if (percentage <= 60) return 'Balanced';
  if (percentage <= 80) return 'Dominant';
  return 'Overwhelming';
}

const PLANE_INTERPRETATIONS: Record<string, Record<PlaneAnalysis['level'], string>> = {
  mental: {
    Deficient: `MENTAL PLANE — DEFICIENT (Line 3-6-9: depleted)\n\nThe Mental Plane represents your relationship with intellect, analysis, and structured thinking. A deficient Mental Plane indicates that logical, analytical thinking is not your natural operating system — not that you lack intelligence, but that your intelligence operates through DIFFERENT CHANNELS (likely intuition or emotional intelligence).\n\nTHE GIFT: You are not imprisoned by your own thinking. Where highly mental types get trapped in loops of overanalysis, you move directly to insight through other pathways. Your mind, when engaged, tends to be clear rather than cluttered.\n\nTHE CHALLENGE: You may struggle with tasks that require sustained analytical focus — detailed planning, systematic problem-solving, or communication that requires precise logical structure. Others may mistakenly perceive you as less intelligent when you are simply processing differently.\n\nTHE PRESCRIPTION: Develop mental discipline not as your primary mode but as a SUPPLEMENTARY tool. Structured practices (daily journaling, learning a system like chess or coding) build the mental musculature without requiring you to become someone you are not.`,

    Developing: `MENTAL PLANE — DEVELOPING (Line 3-6-9: emerging)\n\nThe Mental Plane is present but not dominant in your constitution. You possess the capacity for analytical thought, but it requires conscious effort and tends to be intermittent rather than continuous. Your natural intelligence expresses through intuition, experience, or emotional wisdom more readily than through pure logic.\n\nTHE GIFT: You can think when thinking is needed without being trapped in constant mental activity. Your mind serves your purposes rather than running endlessly on its own momentum.\n\nTHE CHALLENGE: You may find that sustained intellectual work exhausts you more quickly than it does purely mental types — not because you are less capable, but because mental energy is a resource you spend rather than a current you continuously draw.\n\nTHE PRESCRIPTION: Honor your mental energy as a finite resource. Schedule analytical work during your peak energy periods. Supplement your thinking with physical movement — walking meetings, standing desks, or alternating mental and physical tasks throughout the day.`,

    Balanced: `MENTAL PLANE — BALANCED (Line 3-6-9: integrated)\n\nThe Mental Plane is well-integrated in your constitution — you possess genuine intellectual capacity without being dominated by it. You can think analytically when the situation demands it, but your thinking is grounded in other modes of knowing (physical, emotional, intuitive). This balance is relatively rare and represents the ideal: the mind as a SERVANT rather than a master.\n\nTHE GIFT: You combine analytical clarity with practical wisdom. Your conclusions are both logically sound and experientially tested. Others seek your judgment because it integrates what pure thinkers often miss: the human dimension.\n\nTHE CHALLENGE: In environments that demand exclusively analytical performance, you may feel pressure to suppress your other ways of knowing and operate purely intellectually — a mode that disconnects you from your full capacity.\n\nTHE PRESCRIPTION: Trust your balanced constitution. When the purely analytical answer feels wrong, it usually IS wrong — your other ways of knowing are intercepting data the intellect alone cannot process.`,

    Dominant: `MENTAL PLANE — DOMINANT (Line 3-6-9: emphasized)\n\nThe Mental Plane dominates your constitution. You live primarily in the world of ideas, analysis, and structured thought. Your natural impulse is to UNDERSTAND before you act, to analyze before you feel, and to reason your way through problems that others solve through intuition or experience.\n\nTHE GIFT: Your analytical capacity is genuine and formidable. You see logical structures, patterns, and implications that others miss entirely. You can deconstruct complex problems into manageable components and solve them systematically.\n\nTHE CHALLENGE: The mind that is your greatest tool can become your prison. Overanalysis leads to paralysis. Excessive mental activity can disconnect you from your body, your emotions, and your intuition — the very sources of wisdom that would make your thinking more complete.\n\nTHE PRESCRIPTION: Practice GETTING OUT OF YOUR HEAD daily. Physical exercise, creative expression, and embodied practices (dance, yoga, martial arts) are not recreational luxuries but essential counterbalances to your dominant mental mode. Learn to trust decisions that feel right before you can articulate why.`,

    Overwhelming: `MENTAL PLANE — OVERWHELMING (Line 3-6-9: extreme)\n\nThe Mental Plane is not merely dominant but OVERWHELMING in your constitution. You live almost entirely in your head, and the activity there is CONSTANT — a stream of analysis, worry, planning, and conceptual elaboration that rarely ceases. Others may find you brilliant but exhausting; you may find yourself brilliant but exhausted.\n\nTHE GIFT: Your intellectual capacity is extraordinary. You are capable of insights and analytical achievements that others literally cannot access. When your mind is directed toward worthy problems, you produce solutions of genuine significance.\n\nTHE CHALLENGE: The unceasing mental activity is depleting your other resources — physical health, emotional connection, intuitive perception. The mind that never rests eventually breaks. Anxiety, insomnia, and a profound sense of isolation (even when surrounded by people) are common companions.\n\nTHE PRESCRIPTION: Radical intervention in your relationship with thinking is required. Daily embodied practice is NON-NEGOTIABLE — not optional, not "when you have time." Consider meditation, but also consider that some overdeveloped mental types worsen through meditation if it becomes another form of mental control. Physical exhaustion through exercise, manual labor, or sport may be more effective as a direct counterweight.`,
  },
  physical: {
    Deficient: `PHYSICAL PLANE — DEFICIENT (Line 1-4-7: depleted)\n\nThe Physical Plane represents your relationship with the material world, your body, and practical action. A deficient Physical Plane indicates that embodiment — the experience of being IN a body navigating a physical world — is not your natural orientation. You live more in mind, emotion, or spirit than in the physical realm.\n\nTHE GIFT: Your relative disconnection from the physical gives you access to dimensions of experience — intellectual, emotional, spiritual — that physically dominant types may never access. You can be extraordinarily perceptive about the non-physical dimensions of existence.\n\nTHE CHALLENGE: The physical world makes demands that cannot be met through intellect or emotion alone. Practical tasks, physical health, and the maintenance of material existence may feel burdensome or overwhelming. You may neglect your body until it forces attention through illness or exhaustion.\n\nTHE PRESCRIPTION: Approach the physical world not as distraction from your true life but as the FOUNDATION that makes that life possible. Small, consistent physical practices are more effective than ambitious fitness regimes you will abandon. A daily walk, a simple stretching routine, or regular manual work can ground you without overwhelming you.`,

    Developing: `PHYSICAL PLANE — DEVELOPING (Line 1-4-7: emerging)\n\nThe Physical Plane is present but not dominant in your constitution. You inhabit your body and engage with the material world, but physicality is not your primary mode of expression. Your relationship with the physical is functional rather than passionate.\n\nTHE GIFT: You are not trapped in materialism — you can engage with the physical world without being defined by it. You appreciate comfort without being enslaved to luxury. You work with your hands when needed but are not limited to manual labor.\n\nTHE CHALLENGE: In highly physical environments, you may fatigue more quickly than natural athletes or manual workers. Your body may signal distress subtly rather than dramatically, and you may miss these signals until conditions become serious.\n\nTHE PRESCRIPTION: Develop a PHYSICAL PRACTICE you genuinely enjoy — not because you "should exercise" but because the right physical practice becomes a source of pleasure and grounding. Experiment widely: some developing-physical types discover unexpected athletic capacity in specific domains.`,

    Balanced: `PHYSICAL PLANE — BALANCED (Line 1-4-7: integrated)\n\nThe Physical Plane is well-integrated in your constitution. You are comfortable in your body, competent in the material world, and generally effective at translating intention into action. The physical dimension of existence is neither a burden nor an obsession but a natural and reliable aspect of your being.\n\nTHE GIFT: You combine practical effectiveness with other ways of knowing. You can think AND do. You can feel AND act. Your physical health tends to be robust when basic self-care is maintained.\n\nTHE CHALLENGE: The very reliability of your physical plane may lead you to take it for granted — pushing through fatigue, ignoring body signals, and assuming the physical foundation will always support you without deliberate maintenance.\n\nTHE PRESCRIPTION: Celebrate and maintain your physical competence through regular practice. The balanced plane requires less dramatic intervention than the deficient or overwhelming, but it still requires ATTENTION. Treat your body as a valued instrument rather than a reliable appliance.`,

    Dominant: `PHYSICAL PLANE — DOMINANT (Line 1-4-7: emphasized)\n\nThe Physical Plane dominates your constitution. You experience life primarily through your body and through practical action in the material world. Your natural impulse is to DO rather than to think, to move rather than to contemplate, and to engage physically with problems that others approach intellectually or emotionally.\n\nTHE GIFT: Your practical capacity is formidable. You are effective, reliable, and capable of sustained physical action that other types cannot match. In crisis situations, you are the one who acts while others are still processing. You build, you create, you make things real.\n\nTHE CHALLENGE: The physical dominance can crowd out other modes of experience. You may struggle with introspection, emotional nuance, or spiritual perception — not because you lack the capacity but because you have not developed the habit. Others may perceive you as insensitive or unreflective.\n\nTHE PRESCRIPTION: Develop the inner life as deliberately as you have developed the outer. Journaling, therapy, meditation, or artistic practice are not indulgences but the cultivation of capacities your dominant plane has left underdeveloped. The goal is not to become less physical but to balance your formidable physicality with equivalent interior depth.`,

    Overwhelming: `PHYSICAL PLANE — OVERWHELMING (Line 1-4-7: extreme)\n\nThe Physical Plane is not merely dominant but OVERWHELMING. You experience life so intensely through the body and material action that other dimensions of existence barely register. The physical must be attended to CONSTANTLY — activity, stimulation, achievement, acquisition.\n\nTHE GIFT: Your physical drive and practical capacity are extraordinary. You can achieve material success and physical accomplishments that others literally cannot. Your energy is genuinely formidable.\n\nTHE CHALLENGE: The relentless physical focus creates a profound inner poverty. When the body finally demands rest (as it must), you are left with an interior landscape you have never developed — no emotional vocabulary, no spiritual resources, no capacity for quiet contentment. Burnout, addiction, and existential crisis are common when the physical plane finally exhausts itself.\n\nTHE PRESCRIPTION: The development of interior life is no longer optional but URGENT. This does not mean abandoning the physical but complementing it. Begin with small practices of stillness — five minutes of silence daily, one hour weekly without activity or stimulation. Learn to be rather than do. The goal is not physical weakness but the integration of physical strength with emotional and spiritual depth.`,
  },
  emotional: {
    Deficient: `EMOTIONAL PLANE — DEFICIENT (Line 2-5-8: depleted)\n\nThe Emotional Plane represents your relationship with feelings — your own and others'. A deficient Emotional Plane indicates that you experience emotion less intensely or less frequently than most people, and that the emotional dimension of life is not your natural habitat. You process experience through intellect, action, or intuition rather than through feelings.\n\nTHE GIFT: You are not ruled by emotion. In situations where others are overwhelmed by feelings, you remain clear-headed and capable of action. Your judgment is not clouded by sentiment, and your decisions are genuinely rational rather than rationalized emotion.\n\nTHE CHALLENGE: You may struggle to access, identify, or express your own feelings — and equally struggle to perceive or respond appropriately to the feelings of others. This is not coldness but a genuine limitation in emotional perception, much like a color-blind person's limitation in color perception.\n\nTHE PRESCRIPTION: Develop emotional intelligence as a DELIBERATE SKILL rather than expecting it to arise naturally. Practices that systematically build emotional vocabulary (emotion wheels, feeling journals), coupled with safe relationships where emotional expression is explicitly encouraged, can develop capacities that your constitution does not provide spontaneously.`,

    Developing: `EMOTIONAL PLANE — DEVELOPING (Line 2-5-8: emerging)\n\nThe Emotional Plane is present but not dominant. You experience feelings genuinely, but your relationship with emotion may be inconsistent — sometimes flooded, sometimes numb; sometimes deeply empathetic, sometimes inexplicably disconnected. Your emotional life is a developing territory rather than a settled landscape.\n\nTHE GIFT: You possess emotional access without emotional overwhelm. You can feel deeply when the situation calls for it without being incapacitated by feeling. You are in the process of developing emotional intelligence as a conscious capacity rather than an instinctive function.\n\nTHE CHALLENGE: The inconsistency of emotional access can confuse both you and others. People who experienced you as deeply empathetic on one occasion may be shocked by your apparent emotional absence on another. You may question whether your feelings are "real" when they fluctuate so dramatically.\n\nTHE PRESCRIPTION: Emotional inconsistency is not a flaw but a characteristic of a developing emotional plane. Consistent emotional practice — regular check-ins with yourself, honest emotional communication in safe relationships — stabilizes the plane over time. Patience with yourself is essential; the emotional plane develops slowly.`,

    Balanced: `EMOTIONAL PLANE — BALANCED (Line 2-5-8: integrated)\n\nThe Emotional Plane is well-integrated — you possess genuine emotional access, the capacity to empathize deeply with others, and the ability to process emotions without being overwhelmed by them. This balance is a significant gift: you can feel fully while remaining functional.\n\nTHE GIFT: Your emotional intelligence is a genuine resource. You navigate relationships with skill, perceive emotional dynamics that others miss, and provide a kind of emotional presence that is healing simply to be near. Your feelings inform your decisions without distorting them.\n\nTHE CHALLENGE: The very naturalness of your emotional capacity may lead you to overextend — becoming the emotional support for too many people, absorbing others' emotional states without sufficient protection, and neglecting the emotional maintenance that even a balanced plane requires.\n\nTHE PRESCRIPTION: Honor your emotional capacity as the gift it is while establishing clear boundaries around its use. You are not obligated to feel for everyone, heal everyone, or carry everyone's emotional weight. Your emotional health requires the same deliberate maintenance as physical health — regular practices that restore emotional equilibrium.`,

    Dominant: `EMOTIONAL PLANE — DOMINANT (Line 2-5-8: emphasized)\n\nThe Emotional Plane dominates your constitution. You experience life primarily through feelings — your own and others'. Before you think, you feel. Before you act, you feel. The emotional dimension of any situation is not one factor among many but the PRIMARY dimension through which all others are filtered.\n\nTHE GIFT: Your emotional intelligence is extraordinary. You perceive emotional dynamics with an accuracy that approaches the supernatural. Others feel seen, understood, and healed in your presence. You possess what is sometimes called "emotional genius" — the capacity to navigate the human heart with an expertise that intellect alone cannot match.\n\nTHE CHALLENGE: Emotional dominance can make you vulnerable to emotional overwhelm. Your permeable boundaries mean you absorb others' emotional states involuntarily. Decisions that require emotional detachment are genuinely difficult. In environments of high emotional toxicity, you may function poorly or not at all.\n\nTHE PRESCRIPTION: Develop EMOTIONAL BOUNDARIES as a deliberate practice. Distinguish between empathizing (understanding another's feeling) and absorbing (taking on another's feeling). Learn to ask: "Is this mine?" before assuming any feeling you experience is your own. Protect your emotional health with the same vigilance others apply to physical safety.`,

    Overwhelming: `EMOTIONAL PLANE — OVERWHELMING (Line 2-5-8: extreme)\n\nThe Emotional Plane is not merely dominant but OVERWHELMING. You are so porous to emotion — your own and others' — that maintaining emotional equilibrium requires constant, exhausting effort. Your feelings are not just intense but all-encompassing; they color every perception, influence every decision, and can shift your entire reality in moments.\n\nTHE GIFT: Your emotional depth and empathic capacity are of an order that most people cannot comprehend. You are capable of love, compassion, and emotional perception that transcend the ordinary. You sense what others feel before they feel it themselves.\n\nTHE CHALLENGE: The intensity of your emotional experience is genuinely disabling in ordinary circumstances. You may struggle to function in workplaces, social situations, or even relationships because the emotional volume is simply too high. You are prone to emotional exhaustion, burnout, and diagnoses that attempt to pathologize what is fundamentally a constitutional extreme.\n\nTHE PRESCRIPTION: Your emotional life requires STRUCTURED MANAGEMENT — not suppression but regulation. Identify environments, people, and practices that stabilize you versus those that destabilize you, and organize your life accordingly — not from avoidance but from self-knowledge. Like a person with extreme physical sensitivity who cannot tolerate certain environments, your emotional constitution is not a flaw but a FACT that must be honored through intelligent life design.`,
  },
  intuitive: {
    Deficient: `INTUITIVE PLANE — DEFICIENT (Diagonal 1-5-9: depleted)\n\nThe Intuitive Plane represents your connection to direct knowing — the perception of truth that bypasses the ordinary processes of reasoning, feeling, or sensory experience. A deficient Intuitive Plane indicates that you process life through established channels (thought, feeling, action) rather than through the more mysterious channel of direct intuition.\n\nTHE GIFT: You are grounded in verifiable reality. Your decisions are based on evidence, logic, and experience rather than on hunches that may or may not prove reliable. You are not subject to the confusion that afflicts intuitive types who cannot distinguish between genuine guidance and random mental noise.\n\nTHE CHALLENGE: You may miss insights that are not accessible through your established channels. Patterns that require intuitive leaps rather than logical deduction may elude you. Creative and spiritual dimensions of experience may feel inaccessible or unreal.\n\nTHE PRESCRIPTION: Intuition can be developed as a capacity, much like physical fitness. Meditation, dream journaling, and the practice of making small decisions based on "first impulse" (then tracking results) can open intuitive channels that your constitution does not naturally provide.`,

    Developing: `INTUITIVE PLANE — DEVELOPING (Diagonal 1-5-9: emerging)\n\nThe Intuitive Plane is present but inconsistent. You experience moments of genuine intuitive insight — the sudden knowing, the inexplicable certainty, the hunch that proves correct — but these experiences are sporadic rather than reliable. The intuitive channel is opening but not yet fully integrated.\n\nTHE GIFT: You have access to a way of knowing that supplements your rational and emotional intelligence. When intuition speaks, it provides insights your other channels cannot access. You are in the process of discovering a dimension of perception that will become increasingly valuable.\n\nTHE CHALLENGE: The inconsistency of intuitive access makes it difficult to trust. When intuition has been spectacularly right on some occasions and spectacularly wrong on others, you may vacillate between uncritical acceptance of every impulse and cynical rejection of all intuition.\n\nTHE PRESCRIPTION: Approach intuition as a skill to be developed rather than a gift to be received (or not). Keep an intuition journal: record hunches, track outcomes, and notice patterns in when your intuition is most reliable versus when it is not. Over time, you will develop discernment — the capacity to distinguish genuine intuitive insight from projection, wishful thinking, and random mental noise.`,

    Balanced: `INTUITIVE PLANE — BALANCED (Diagonal 1-5-9: integrated)\n\nThe Intuitive Plane is well-integrated — you possess reliable access to direct knowing that supplements and enriches your other ways of knowing. Your intuition is not a mysterious force that occasionally overwhelms you but a trusted advisor whose counsel you have learned to recognize and heed.\n\nTHE GIFT: You combine rational analysis, emotional intelligence, and intuitive perception in a genuinely integrated way. You can think through a problem, feel your way into it, AND sense its deeper dimensions — then synthesize all three into a response that is wiser than any single channel could produce.\n\nTHE CHALLENGE: The balance itself can be misleading. Because your intuition is generally reliable, you may fail to notice when it is not — when projection or wishful thinking is masquerading as genuine guidance. The balanced intuitive sometimes needs to verify.\n\nTHE PRESCRIPTION: Maintain your intuitive channel through regular practice — meditation, time in nature, creative expression. The intuitive plane, like all planes, requires maintenance to remain healthy. Trust your intuition while periodically subjecting it to the discipline of verification, especially in high-stakes decisions.`,

    Dominant: `INTUITIVE PLANE — DOMINANT (Diagonal 1-5-9: emphasized)\n\nThe Intuitive Plane dominates your constitution. You perceive reality through a channel that is more direct, more immediate, and more mysterious than the ordinary processes of thought or feeling. You often KNOW without being able to explain how you know. Others find this unsettling or miraculous depending on context.\n\nTHE GIFT: Your intuitive capacity is authentic and formidable. You perceive patterns, connections, and implications that others cannot access through any amount of analysis. Your insights arrive whole and complete, bypassing the step-by-step reasoning that others require. In creative, strategic, and spiritual domains, you operate at a level others cannot match.\n\nTHE CHALLENGE: Strong intuition without equivalent grounding in rational thought or emotional intelligence can become unreliable. You may act on intuitive impulses that are accurate about the WHAT but wrong about the HOW or WHEN. Others may dismiss your insights because you cannot explain your reasoning, creating isolation and frustration.\n\nTHE PRESCRIPTION: Develop the CAPACITY TO ARTICULATE your intuitive insights. This does not mean abandoning intuition for logic but building the bridge between them — learning to translate intuitive knowing into forms others can understand. Additionally, learn to test your intuition against reality periodically. Even the most gifted intuitive benefits from the discipline of verification.`,

    Overwhelming: `INTUITIVE PLANE — OVERWHELMING (Diagonal 1-5-9: extreme)\n\nThe Intuitive Plane is not merely dominant but OVERWHELMING. You are so open to intuitive perception that establishing boundaries between your own psyche and the collective unconscious is difficult or impossible. Insights, visions, and knowing arrive unbidden and often unmanageably — a fire hose of psychic data that you did not request and cannot turn off.\n\nTHE GIFT: Your intuitive and potentially psychic capacity is of a genuinely extraordinary order. You perceive dimensions of reality that most people do not believe exist. You are, in the most literal sense, a channel for information that transcends ordinary perception.\n\nTHE CHALLENGE: Unmanaged intuitive overwhelm is disabling. The inability to distinguish between your own thoughts and externally received impressions, the constant intrusion of psychic data, and the sheer exhaustion of processing non-ordinary perception can make ordinary life extraordinarily difficult. Psychological confusion, spiritual crisis, and social isolation are common.\n\nTHE PRESCRIPTION: Grounding is ESSENTIAL and non-negotiable. Physical practices, time in nature, manual work, and deliberate engagement with the material world provide the anchor that makes your intuitive capacity sustainable. Additionally, seek training in psychic protection and energetic boundaries — not because you should suppress your gift but because a gift without the capacity to regulate it is a burden. The goal is not less intuition but more control over WHEN and HOW you are intuitive.`,
  },
};

function planeScore(counts: Record<number, number>, line: number[]): number {
  return line.reduce((sum, n) => sum + (counts[n] || 0), 0);
}

export function analyzePlanes(numberCounts: Record<number, number>): PlaneResult {
  const ps = (line: number[]) => planeScore(numberCounts, line);
  const mentalScore = ps([3, 6, 9]);
  const physicalScore = ps([1, 4, 7]);
  const emotionalScore = ps([2, 5, 8]);
  const intuitiveScore = ps([1, 5, 9]);

  // Max per cell is undefined (any count possible), normalize by relative proportion
  const total = mentalScore + physicalScore + emotionalScore + intuitiveScore || 1;
  const mPct = Math.round((mentalScore / total) * 100);
  const pPct = Math.round((physicalScore / total) * 100);
  const ePct = Math.round((emotionalScore / total) * 100);
  const iPct = Math.round((intuitiveScore / total) * 100);

  const mental: PlaneAnalysis = { name: 'Mental', score: mentalScore, maxScore: total, percentage: mPct, cells: [3, 6, 9], level: getLevel(mPct), interpretation: PLANE_INTERPRETATIONS.mental[getLevel(mPct)] };
  const physical: PlaneAnalysis = { name: 'Physical', score: physicalScore, maxScore: total, percentage: pPct, cells: [1, 4, 7], level: getLevel(pPct), interpretation: PLANE_INTERPRETATIONS.physical[getLevel(pPct)] };
  const emotional: PlaneAnalysis = { name: 'Emotional', score: emotionalScore, maxScore: total, percentage: ePct, cells: [2, 5, 8], level: getLevel(ePct), interpretation: PLANE_INTERPRETATIONS.emotional[getLevel(ePct)] };
  const intuitive: PlaneAnalysis = { name: 'Intuitive', score: intuitiveScore, maxScore: total, percentage: iPct, cells: [1, 5, 9], level: getLevel(iPct), interpretation: PLANE_INTERPRETATIONS.intuitive[getLevel(iPct)] };

  const planes = [mental, physical, emotional, intuitive];
  planes.sort((a, b) => b.percentage - a.percentage);
  const dominantPlane = planes[0]!.name;
  const weakestPlane = planes[3]!.name;

  const DOMINANT_SYNTHESIS: Record<string, string> = {
    Mental: 'You are constitutionally oriented toward the life of the mind. Your primary mode of engagement is THINKING — analysis, planning, conceptual understanding. The challenge is that excessive mental activity disconnects you from body, feelings, and intuition. The integration is to USE your mental dominance as a tool rather than letting it use you.',
    Physical: 'You are constitutionally oriented toward action and the material world. Your primary mode of engagement is DOING — building, moving, achieving tangible results. The challenge is that excessive physical activity crowds out interior life. The integration is to develop the inner dimensions (thought, feeling, intuition) to complement your natural effectiveness.',
    Emotional: 'You are constitutionally oriented toward feeling and relationship. Your primary mode of engagement is CONNECTING — empathizing, nurturing, experiencing the emotional dimension of life. The challenge is that excessive emotional openness creates vulnerability to overwhelm. The integration is to develop boundaries that protect without closing the heart.',
    Intuitive: 'You are constitutionally oriented toward direct knowing and spiritual perception. Your primary mode of engagement is SENSING — the immediate apprehension of truth beyond logic or feeling. The challenge is that excessive intuitive openness creates confusion between genuine guidance and psychic noise. The integration is to ground your intuition in practical life.',
  };

  const synthesis = `PLANE SYNTHESIS — Dominant: ${dominantPlane} / Weakest: ${weakestPlane}\n\n${DOMINANT_SYNTHESIS[dominantPlane] || ''}\n\nYOUR FOUR PLANES:\n• Mental (${mental.percentage}%): ${mental.level} — Line of intellect, logic, and structured thought\n• Physical (${physical.percentage}%): ${physical.level} — Line of body, action, and material engagement\n• Emotional (${emotional.percentage}%): ${emotional.level} — Line of feeling, empathy, and relationship\n• Intuitive (${intuitive.percentage}%): ${intuitive.level} — Line of direct knowing and spiritual perception\n\nThe relationship between your strongest plane (${dominantPlane}) and your weakest plane (${weakestPlane}) defines your primary growth edge. The tendency will be to rely entirely on the ${dominantPlane} and neglect the ${weakestPlane} — but genuine integration requires developing the neglected plane to at least functional capacity while maintaining the dominant plane's natural strength.`;

  return { mental, physical, emotional, intuitive, dominantPlane, weakestPlane, synthesis };
}
